# Generated by Django 4.2.18 on 2025-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released'), ('Coming Soon', 'Coming Soon'), ('Cancelled', 'Cancelled'), ('Now Showing', 'Now Showing')], default='Pending', max_length=15),
        ),
    ]
