# Generated by Django 4.2.18 on 2025-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showing', '0002_alter_showing_movie_alter_showing_date_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='time',
            field=models.TimeField(),
        ),
    ]
