# Generated by Django 4.2.18 on 2025-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showing', '0003_alter_showing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='includes_3d_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showing',
            name='includes_popcorn',
            field=models.BooleanField(default=False),
        ),
    ]
